// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: /home/up/w/xar-network/x/bonds/keeper
// ALIASGEN: /home/up/w/xar-network/x/bonds/types
// ALIASGEN: /home/up/w/xar-network/x/bonds/exported
package bonds

import (
	"github.com/xar-network/xar-network/x/bonds/exported"
	"github.com/xar-network/xar-network/x/bonds/keeper"
	"github.com/xar-network/xar-network/x/bonds/types"
)

const (
	DefaultParamspace          = keeper.DefaultParamspace
	DefaultCodespace           = types.DefaultCodespace
	CodeInvalidDeposit         = types.CodeInvalidDeposit
	CodeInvalidInput           = types.CodeInvalidInput
	CodeInvalidAddress         = types.CodeInvalidAddress
	CodeUnauthorized           = types.CodeUnauthorized
	CodeInternal               = types.CodeInternal
	CodeUnknownRequest         = types.CodeUnknownRequest
	EventTypeCompleteUnbonding = types.EventTypeCompleteUnbonding
	EventTypeBond              = types.EventTypeBond
	EventTypeUnbond            = types.EventTypeUnbond
	AttributeKeyCompletionTime = types.AttributeKeyCompletionTime
	AttributeKeyDepostior      = types.AttributeKeyDepostior
	AttributeValueCategory     = types.AttributeValueCategory
	ModuleName                 = types.ModuleName
	StoreKey                   = types.StoreKey
	QuerierRoute               = types.QuerierRoute
	RouterKey                  = types.RouterKey
	QueryDeposit               = types.QueryDeposit
	QueryUnbondingDeposit      = types.QueryUnbondingDeposit
	QueryPool                  = types.QueryPool
	QueryParameters            = types.QueryParameters
)

var (
	// functions aliases
	NewKeeper                     = keeper.NewKeeper
	ParamKeyTable                 = keeper.ParamKeyTable
	NewQuerier                    = keeper.NewQuerier
	RegisterCodec                 = types.RegisterCodec
	NewDeposit                    = types.NewDeposit
	MustMarshalDeposit            = types.MustMarshalDeposit
	MustUnmarshalDeposit          = types.MustUnmarshalDeposit
	UnmarshalDeposit              = types.UnmarshalDeposit
	NewUnbondingDeposit           = types.NewUnbondingDeposit
	NewUnbondingDepositEntry      = types.NewUnbondingDepositEntry
	MustMarshalUBD                = types.MustMarshalUBD
	MustUnmarshalUBD              = types.MustUnmarshalUBD
	UnmarshalUBD                  = types.UnmarshalUBD
	ErrNilDepositorAddr           = types.ErrNilDepositorAddr
	ErrZeroAmount                 = types.ErrZeroAmount
	ErrBadDenom                   = types.ErrBadDenom
	ErrBadDepositAddr             = types.ErrBadDepositAddr
	ErrBadDepositAmount           = types.ErrBadDepositAmount
	ErrNoDeposit                  = types.ErrNoDeposit
	ErrBadDepositorAddr           = types.ErrBadDepositorAddr
	ErrNoDepositorForAddress      = types.ErrNoDepositorForAddress
	ErrNotEnoughDepositTokens     = types.ErrNotEnoughDepositTokens
	ErrNotMature                  = types.ErrNotMature
	ErrNoUnbondingDeposit         = types.ErrNoUnbondingDeposit
	ErrMaxUnbondingDepositEntries = types.ErrMaxUnbondingDepositEntries
	NewGenesisState               = types.NewGenesisState
	NewMultiBondHooks             = types.NewMultiBondHooks
	GetDepositKey                 = types.GetDepositKey
	GetUBDKey                     = types.GetUBDKey
	GetUnbondingDepositTimeKey    = types.GetUnbondingDepositTimeKey
	NewParams                     = types.NewParams
	MustUnmarshalParams           = types.MustUnmarshalParams
	UnmarshalParams               = types.UnmarshalParams
	NewPool                       = types.NewPool
	NewQueryDepositorParams       = types.NewQueryDepositorParams
	NewQueryBondsParams           = types.NewQueryBondsParams

	// variable aliases
	ModuleCdc            = types.ModuleCdc
	DepositKey           = types.DepositKey
	UnbondingDepositKey  = types.UnbondingDepositKey
	UnbondingQueueKey    = types.UnbondingQueueKey
	KeyUnbondingTime     = types.KeyUnbondingTime
	KeyMaxEntries        = types.KeyMaxEntries
	KeyBondDenom         = types.KeyBondDenom
	KeyNotBondedPoolName = types.KeyNotBondedPoolName
	KeyBondedPoolName    = types.KeyBondedPoolName
)

type (
	Keeper                = keeper.Keeper
	Deposit               = types.Deposit
	Deposits              = types.Deposits
	UnbondingDeposit      = types.UnbondingDeposit
	UnbondingDepositEntry = types.UnbondingDepositEntry
	UnbondingDeposits     = types.UnbondingDeposits
	CodeType              = types.CodeType
	GenesisState          = types.GenesisState
	GenesisStateData      = types.GenesisStateData
	MultiBondHooks        = types.MultiBondHooks
	Params                = types.Params
	Pool                  = types.Pool
	QueryDepositorParams  = types.QueryDepositorParams
	QueryBondsParams      = types.QueryBondsParams
	DepositI              = exported.DepositI
)
