// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: /home/up/w/xar-network/x/governors/types
// ALIASGEN: /home/up/w/xar-network/x/governors/keeper
package governors

import (
	"github.com/xar-network/xar-network/x/governors/keeper"
	"github.com/xar-network/xar-network/x/governors/types"
)

const (
	DefaultCodespace     = types.DefaultCodespace
	ModuleName           = types.ModuleName
	StoreKey             = types.StoreKey
	QuerierRoute         = types.QuerierRoute
	RouterKey            = types.RouterKey
	DefaultBondDenom     = types.DefaultBondDenom
	DefaultUnbondingTime = types.DefaultUnbondingTime
	DefaultMaxEntries    = types.DefaultMaxEntries
	BondedPoolName       = types.BondedPoolName
	NotBondedPoolName    = types.NotBondedPoolName
	DefaultParamspace    = types.DefaultParamspace
)

var (
	// functions aliases
	RegisterCodec       = types.RegisterCodec
	NewGenesisState     = types.NewGenesisState
	DefaultGenesisState = types.DefaultGenesisState
	NewMsgBond          = types.NewMsgBond
	NewMsgUnbond        = types.NewMsgUnbond
	NewParams           = types.NewParams
	MustUnmarshalParams = types.MustUnmarshalParams
	UnmarshalParams     = types.UnmarshalParams
	DefaultParams       = types.DefaultParams

	// variable aliases
	ModuleCdc  = types.ModuleCdc
	KeyBonds   = types.KeyBonds
	NewKeeper  = keeper.NewKeeper
	NewQuerier = keeper.NewQuerier
)

type (
	AccountKeeper = types.AccountKeeper
	SupplyKeeper  = types.SupplyKeeper
	BondHooks     = types.BondHooks
	GenesisState  = types.GenesisState
	MsgBond       = types.MsgBond
	MsgUnbond     = types.MsgUnbond
	Params        = types.Params
	Keeper        = keeper.Keeper
)
